language: php

php:
- 7.3
- 7.4

install:
- travis_retry composer install --no-interaction --no-suggest

script:
- composer test -- --coverage-clover=coverage.xml

branches:
  only:
  - master
  - dev
cache:
  directories:
  - $HOME/.composer/cache